const WS_CONNECTED = 'ws/WS_CONNECTED';
const WS_NEXT_HAND = 'ws/WS_NEXT_HAND';
const WS_HERO_FOLD = 'ws/WS_HERO_FOLD';
const WS_HERO_CHECK = 'ws/WS_HERO_CHECK';
const WS_HERO_CALL = 'ws/WS_HERO_CALL';
const WS_HERO_BET = 'ws/WS_HERO_BET';

export {WS_CONNECTED, WS_NEXT_HAND, WS_HERO_FOLD, WS_HERO_BET, WS_HERO_CALL, WS_HERO_CHECK};